# Generated by Django 5.0.6 on 2026-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_reservation_user_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='segment',
            field=models.CharField(choices=[('e', 'Economy'), ('c', 'Comfort'), ('p', 'Premium'), ('s', 'SUV')], default='e', max_length=1),
        ),
    ]
