# Generated by Django 5.0.6 on 2026-03-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Hibrit'), ('electric', 'Elektrik')], default='gasoline', max_length=20, verbose_name='Yakıt Tipi'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_ac',
            field=models.BooleanField(default=True, verbose_name='Klima Var mı?'),
        ),
    ]
