# Generated by Django 5.0.6 on 2026-04-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_fuel_type_car_has_ac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='user_rent_date',
        ),
    ]
