"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# django-environ setup
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # drf_package
    'rest_framework',
    'dj_rest_auth',
    'rest_framework.authtoken',
    'corsheaders',
    # my_apps
    'users',
    'car',
    # AWS S3 için gerekli uygulama
    'storages',
    # AWS S3 silme işlemi için;
    'django_cleanup.apps.CleanupConfig',
    # e-posta ile giriş ve sosyal medya ile giriş için gerekli uygulamalar
    'django.contrib.sites',  # Allauth için zorunlu
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration', # Kayıt özellikleri için
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # EN ÜSTTE OLMALI
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


SITE_ID = 1 # Genelde 1'dir, admin panelinden kontrol edilebilir

# --- Allauth Ayarları (Yeni Versiyon Uyumlu) ---

# Giriş yöntemi olarak sadece e-postayı belirler
ACCOUNT_LOGIN_METHODS = {'email'}

# Kayıt formunda hangi alanların zorunlu olduğunu belirler 
# (Yıldız işareti zorunlu olduğunu temsil eder)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# E-postaların benzersiz olmasını ve doğrulama gerekmediğini belirtmeye devam ediyoruz
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Kullanıcı adı (username) alanını tamamen devre dışı bırakmak için (isteğe bağlı)
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None #? google login için username alanını devre dışı bırakmak istiyorsak bu satırı ekleyebiliriz, ancak bazı durumlarda sorun çıkarabilir. O yüzden şimdilik yorum satırı olarak bırakıyoruz.

# Yerel geliştirme için e-postaları terminale yazdırır
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AUTHENTICATION_BACKENDS = [
    # Django'nun kendi auth sistemi
    'django.contrib.auth.backends.ModelBackend',
    # Allauth'un özel auth sistemi
    'allauth.account.auth_backends.AuthenticationBackend',
]



# Kullanıcı adı giriş yöntemini e-posta yapıyoruz
# ACCOUNT_AUTHENTICATION_METHOD = 'email' #? Bu satır eski versiyonlarda kullanılıyordu, yeni versiyonda ACCOUNT_LOGIN_METHODS ile aynı işlevi görüyor. O yüzden bu satırı yorum satırı yapıyoruz.
ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_EMAIL_REQUIRED = True #? Eski ACCOUNT_EMAIL_REQUIRED ve ACCOUNT_USERNAME_REQUIRED gibi ayarlar, artık tek bir liste olan ACCOUNT_SIGNUP_FIELDS altında birleştirildi. Buradaki * işareti, o alanın zorunlu olduğunu belirtir. O yüzden bu satırları yorum satırı yapıyoruz.
# ACCOUNT_USERNAME_REQUIRED = False  # Kayıt formunda kullanıcıya sorma (biz üreteceğiz) #? Eski ACCOUNT_EMAIL_REQUIRED ve ACCOUNT_USERNAME_REQUIRED gibi ayarlar, artık tek bir liste olan ACCOUNT_SIGNUP_FIELDS altında birleştirildi. Buradaki * işareti, o alanın zorunlu olduğunu belirtir.
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*'] # Kayıt formunda sadece e-posta ve şifre alanlarını göster, ikisini de zorunlu yap!
ACCOUNT_UNIQUE_EMAIL = True # E-posta adreslerinin benzersiz olmasını sağlar
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# 🎯 İŞTE SİHİRLİ SATIRLAR:
# E-posta adresinden (örn: umit@gmail.com) otomatik kullanıcı adı (umit) üretir.
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'

# Eğer aynı isimli başka biri gelirse (örn: başka bir umit@...), 
# çakışmayı önlemek için sonuna rastgele karakter ekle:
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'
# Eğer kullanıcı adı çakışırsa sonuna rastgele karakter ekleyerek benzersiz yapar
SOCIALACCOUNT_AUTO_SIGNUP = True




# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

REST_AUTH = {
    'TOKEN_SERIALIZER': 'users.serializers.CustomTokenSerializer',
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserDetailSerializer',
}

# CORS
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_ALL_ORIGINS = True # Geliştirme aşamasında her yerden gelen isteğe izin ver

# CSRF
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')


# AWS S3 Ayarları
# INSTALLED_APPS listesine 'storages' eklemeyi unutma!
# INSTALLED_APPS += ['storages'] # eklendi

# AWS S3 Ayarları
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')

# Medya dosyalarını S3'e yönlendir
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Dosyaların URL yapısı
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# Dosyaların yüklendiğinde herkes tarafından okunabilir olmasını sağlar
AWS_QUERYSTRING_AUTH = False  # Linklerin sonunda karmaşık imzalar olmasın
# AWS_DEFAULT_ACL = 'public-read' # Yüklenen her dosya "public-read" olsun
AWS_DEFAULT_ACL = None  # Django'nun ACL(AccessControlList) göndermesini engeller


# # Google account settings.py dosyasının en altına ekle:
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('GOOGLE_CLIENT_ID'), # .env'den okuyacak
            'secret': env('GOOGLE_CLIENT_SECRET'), # .env'den okuyacak
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# settings.py sonuna ekle
if not DEBUG: # Sadece prodüksiyonda (Railway'de) çalışır
    SITE_ID = 1